### ISSUE TITLE
Error in YouTube(video_url).streams.... function

### ISSUE THREAD

**Issue by metaphorz** [haltakov/natural-language-youtube-search#9]
I get an error when going through this Colab notebook in the cell where the "streams =" is executed. I verified that the youtube video exists.

HTTPError                                 Traceback (most recent call last)

<ipython-input-4-8a59b481311f> in <module>()
      2 
      3 # Choose a video stream with resolution of 360p
----> 4 streams = YouTube(video_url).streams.filter(adaptive=True, subtype="mp4", resolution="360p", only_video=True)
      5 
      6 # Check if there is a valid stream

12 frames

/usr/lib/python3.7/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by zhouyang-bigdata** [comment]
> I tried your colab. I also used another video url for test purposes: https://www.youtube.com/watch?v=PGMu_Z89Ao8
> 
> Colab Pro. Runtime type: GPU
> 
> The error (perhaps different than the other one) is here:
> <img alt="Screen Shot 2021-08-25 at 4 57 53 PM" width="878" src="https://user-images.githubusercontent.com/3519631/130870077-89476806-8231-4118-be86-3a0b6ee570f8.png">

I have encountered the same problem

**Comment by zhouyang-bigdata** [comment]
> > I tried your colab. I also used another video url for test purposes: https://www.youtube.com/watch?v=PGMu_Z89Ao8
> > Colab Pro. Runtime type: GPU
> > The error (perhaps different than the other one) is here:
> > <img alt="Screen Shot 2021-08-25 at 4 57 53 PM" width="878" src="https://user-images.githubusercontent.com/3519631/130870077-89476806-8231-4118-be86-3a0b6ee570f8.png">
> 
> I have encountered the same problem

Problem solving: Change the name of the downloaded video to **.mp4

**Comment by zhouyang-bigdata** [comment]
> > I tried your colab. I also used another video url for test purposes: https://www.youtube.com/watch?v=PGMu_Z89Ao8
> > Colab Pro. Runtime type: GPU
> > The error (perhaps different than the other one) is here:
> > <img alt="Screen Shot 2021-08-25 at 4 57 53 PM" width="878" src="https://user-images.githubusercontent.com/3519631/130870077-89476806-8231-4118-be86-3a0b6ee570f8.png">
> 
> I have encountered the same problem

Problem solving: Change the name of the downloaded video to **.mp4

**Comment by haltakov** [comment]
Hey @zhouyang-bigdata, thanks for the suggestion. I guess something in the youtube download library changed so this stopped working. Should be solved with this PR: https://github.com/haltakov/natural-language-youtube-search/pull/10
